resources:
  - ../../../../spot-render-api/k8s/services.yaml
  - ../../../../spot-render-api/k8s/analysis.yaml
  - ../../../../spot-render-api/k8s/rollout.yaml
  - ../../../../spot-render-api/k8s/hpa.yaml
  - ../../../../spot-render-api/k8s/servicemonitor.yaml
patchesStrategicMerge:
  - rollout-patch.yaml
