apiVersion: v1
kind: Secret
metadata:
  name: spot-render-backend-secrets
  namespace: spot-render
type: Opaque
stringData:
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""
  DEFAULT_RENDER_ADMIN_USER: "admin"
  DEFAULT_RENDER_ADMIN_PASSWORD: "admin"
