apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spot-ai
resources:
  - ./ollama.yaml
commonLabels:
  environment: aws
  spot.ai/managed: "true"
configMapGenerator:
  - name: ollama-config
    envs:
      - env-params.env
configurations:
  - transformer.yaml
